# Generated by Django 4.0.3 on 2023-05-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bongbu', '0002_realty_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty_News_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bongbu.realty_news')),
            ],
        ),
    ]
